### ISSUE TITLE
System.IO

### ISSUE THREAD

**Issue by gwnrobin** [Studio-23D/Ontwikkelink#18]
URl: https://github.com/Studio-23D/Ontwikkelink/blob/feature/imageCreator/Assets/Scripts/Screenshot/ScreenshotButton.cs

System.IO is used multiple times so what could have been done is
Using System.IO on top of your script

**Comment by ghost** [comment]
Did this for good practice, but it wasn't in favor of the development team. 
Removed every System.IO and instead used the namespace.
