### ISSUE TITLE
Feedback: Split this script into two separate scripts

### ISSUE THREAD

**Issue by JesseyStend** [Studio-23D/Ontwikkelink#19]
This script is used for both taking a screenshot and saving those

Try sliting those 2 into 2 separate scripts for readability and usability

Link: [Screenshot button](https://github.com/Studio-23D/Ontwikkelink/blob/feature/imageCreator/Assets/Scripts/Screenshot/ScreenshotButton.cs)

**Comment by ghost** [comment]
Separated the ScreenshotButton script into ScreenshotCapture, ScreenshotSaving, and ScreenshotButton. Each with dedicated and agile functionality.
