### ISSUE TITLE
Multiple childs possibility

### ISSUE THREAD

**Issue by wesleycats** [Studio-23D/Ontwikkelink#21]
Due to not checking for other childs, there is a possibility for a bug where there is still the existence of other childs.

https://github.com/Studio-23D/Ontwikkelink/blob/d4d37ed6bcd5426ed2c834164759ae51a3325152/Assets/Scripts/Character/CharacterAppearance.cs#L17-L20

**Comment by gwnrobin** [comment]
fixed it by looping though the child and deleting everthing there is
